# This is a basic workflow to help you get started with Actions

name: Get AWS creds

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# permissions
permissions:
  id-token: write
  contents: read
  
jobs:
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    steps:
      - name: whatever
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          audience: sts.amazonaws.com.
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::905418229120:role/t_rodman
          role-session-name: GitHub_to_AWS_via_FederatedOIDC

  # Hello from AWS: WhoAmI
  - name: Sts GetCallerIdentity
    run: |
      aws sts get-caller-identity

Outputs:
  Role:
    Value: !GetAtt Role.Arn 
